#!/bin/bash

# This is run on the server to deploy the dockerized kernel, to synchronize the repositories, and to reload on error
ROOT="$HOME/root"
SYNC="$ROOT/boot/lib/git-sync"

if [ ! -x "$SYNC" ]; then
  echo "Unable to find git-sync in boot repository. Exiting..."
  exit 1
fi

sync_root() {
  pushd "$ROOT"
  
  $SYNC

  popd
}

echo "Deploy script running on remote server."

sync_root
