#!/bin/bash

# Install the Hacker Union server on a compatible cloud provider
# Tested against AWS running Amazon Linux image

if (( $# < 3 )); then
  echo -e "Push complete server to a remote host.\n\nUsage: $0 ssh-url private-key secret-key\n"
  exit 1
fi

URL=$1
PEM=$2
SECRET=$3
REPO=$4

if [ ! -f "$PEM" ]; then
  echo "Your private key does not exist."
  exit 2
fi

if [ ! -f "$SECRET" ]; then
  echo "Your secret key does not exist."
  exit 3
fi

echo "Push new server to \"$URL\" based on \"$REPO\"?"
read -p "(y/n) " RESP

if echo $RESP | grep -qvi '^ye\?s\?$'; then
  echo "Aborting!"
  exit 4
fi

echo "Copying secret key..."
scp -i "$PEM" "$SECRET" "$URL":/tmp/

echo "Installing dependencies..."
ssh -ti "$PEM" "$URL" sudo yum install -y git docker

echo "Starting docker..."
ssh -ti "$PEM" "$URL" sudo service docker restart

echo "Cloning root repository..."
ssh -ti "$PEM" "$URL" git clone --recursive "$REPO" root

echo "Running deploy script..."
ssh -ti "$PEM" "$URL" bash root/boot/deploy

echo "Done!"
